### ISSUE TITLE
Seed not working

### ISSUE THREAD

**Issue by khodor14** [jermp/pthash#13]
Hello @jermp @ByteHamster 

I tried pthash on artificial data, it worked. However when I moved to the hash values of k-mers, it is raising an error related to the seed (see below).
`c = 6
alpha = 0.94
num_keys = 21817
table_size = 23209
num_buckets = 9083
 == map+sort took: 0.002 seconds
 == merged 0% pairsterminate called after throwing an instance of 'pthash::seed_runtime_error'
  what():  seed did not work
`
I tried different values of seed, but they are not working.

What could be the problem?

**Comment by roberto-trani** [comment]
Hi @khodor14 , could it be that your input contains duplicate keys?

**Comment by jermp** [comment]
Yes, surely due to duplicate keys in the input.
Beware that using 64-bit hashes with more than ~2B keys, will result in hashes to collide with relatively high probability.

Best,
-Giulio

**Comment by khodor14** [comment]
thanks alot!
