### ISSUE TITLE
missing include

### ISSUE THREAD

**Issue by yhhshb** [jermp/pthash#15]
Hi @jermp ,
I think pthash/include/encoders/util.hpp is missing the cstdint and cassert headers.
g++ 12.3 complains about uintX_t definitions and asserts.

**Comment by jermp** [comment]
Hi @yhhshb, which header?

**Comment by jermp** [comment]
I do not have this issue. It just compiles fine on `gcc version 12.3.0`.
I think the problem you're seeing is because you're taking just the file util.hpp and place it in another project. Right?

**Comment by jermp** [comment]
Hi @yhhshb, can you please confirm?

**Comment by yhhshb** [comment]
Hi @jermp ,

No, I did not take util.hpp alone.
I use the whole repository as a dependency of other projects.

**Comment by jermp** [comment]
Ah ok. Strange that I cannot replicate the issue from PTHash itself. Anyway, I've just added the missing includes.
