### ISSUE TITLE
-i can't read from a non-mmap-friendly input file when using --external

### ISSUE THREAD

**Issue by zacchiro** [jermp/pthash#18]
It is handy to pass "streaming" content as input to `build -i`, e.g., by using shell process substitution like this: `build -i <(zstdcat foo.txt.zst)`.

Unfortunately that does not work when `--external` is used.
Apparently in that case (and only in that case) the input file passed to `-i` is mmap-ed, which obviously fail when the input file is not a regular file (a FIFO, in the case of process substitution).

Would it be possible to either avoid mmap-ing the input file even when `--external` is used or, alternatively, to have an option to inhibit that selectively?

Thanks!

**Comment by jermp** [comment]
Hi @zacchiro,
now it should be done, as of https://github.com/jermp/pthash/commit/0d09102915064e4ca74496a136619b9aa4e62a2e.
Now, if you specify `--external` it does not use mmap anymore by default. To enable mmap, use `--mmap`.

Best,
-Giulio

**Comment by zacchiro** [comment]
Confirmed, it works for me now. Thanks! Closing the issue.
