### ISSUE TITLE
duplicate hash values on additive displacement

### ISSUE THREAD

**Issue by khodor14** [jermp/pthash#42]
Hi,

I was using additive displcament in the  [play branch](https://github.com/jermp/pthash/tree/play), however it is generating duplicate hash values.

You can download from [here](https://filesender.renater.fr/?s=download&token=1b8edea5-1357-4645-ace8-ff033a921087) the keyset that I was using. The file I am using is kmers_64bits_5776.txt.

What could be the issue?

Best,

**Comment by stefanfred** [comment]
Thank for reporting this issue. Should be fixed with #43

**Comment by jermp** [comment]
Hi,
I also confirm it now works correctly. I tested it with:

     ./build -n 5775 -i kmers_64bits_5776.txt -l 12.0 -a 0.94 -e R-R -r add -b skew -s 1234567890 -t 2 --verbose -q 1000000 --check

Thanks @stefanfred for the fix!

Best,
-Giulio

**Comment by khodor14** [comment]
Hi,

@stefanfred @jermp thanks alot.

Best,
