### ISSUE TITLE
Compile issue in gcc 10.2.1

### ISSUE THREAD

**Issue by beling** [jermp/pthash#5]
The following line in `util.hpp` causes compile error in gcc 10.2.1:
`#define MAX_BUCKET_SIZE static_cast<bucket_size_type>(100)`
error message `expected unqualified-id before ‘static_cast’`

I found that replacing that line with the following fix the problem:
`constexpr bucket_size_type MAX_BUCKET_SIZE = 100;`

**Comment by jermp** [comment]
Hi,
well it does not produce any error in gcc 11.x.x nor clang.
Anyway, thanks for reporting! I'm updating the line as you suggested.

**Comment by jermp** [comment]
b9a0c372cd4c12219f9508f2edac24347aaaca98
